# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  distribute:
    # The type of runner that the job will run on
    # runs-on: ubuntu-latest

    runs-on: ${{ matrix.os }}                           
    strategy:                             
      matrix:                               
        os: [ubuntu-latest]                               
        include:                                 
          - os: ubuntu-latest                                   
            flutter_path: /opt/hostedtoolcache/flutter

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # - uses: actions/setup-java@v1
      #   with:
      #     java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.5.x"
          # channel: "beta"
      # - uses: actions/cache@v1
      #   with:
      #     path: ${{ matrix.flutter_path }}
      #     key: ${{ runner.os }}-flutter-install-cache-${{ env.flutter_version }}
      - run: flutter pub get


      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
          bundler-cache: true

      # - uses: maierj/fastlane-action@v2.0.1
      #   with:
      #     lane: "distribute"
      #     subdirectory: "android"
      # work please

      - name: setup fastlane
        working-directory: ./android
        run: bundle install
      - name: flutter build apk
        working-directory: ./android
        run: flutter build apk
      - name: distribute to firebase
        working-directory: ./android
        # run: |
        #   bundle exec fastlane add_plugin firebase_app_distribution
        #   bundle exec fastlane android distribute
        run: bundle exec fastlane android distribute
        env:
          FIREBASE_APP_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
